Select
emp.job,emp.deptno, dep.deptno
from
emp, dept dep
where
emp.deptno= dep.deptno;


SELECT E.EMPNO, E.ENAME, D.DEPTNO, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL >= 3000
ORDER BY D.DEPTNO, E.EMPNO;

-- RIGHT OUTER JOIN(왼쪽에 NULL값이 나온다)
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO, E2.ENAME, E2.JOB
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO;

-- LEFT OUTER JOIN(오른쪽에 NULL값이 나온다)
SELECT E1.EMPNO, E1.ENAME, E1.MGR, E2.EMPNO, E2.ENAME,E2.JOB
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+);

-- ANSI 코드 : FROM 절에 INNER JOIN, OUTER JOIN을 표시하며, 조건을 ON을 사용해 표현할 수 있다.
SELECT A.EMP_ID, A.EMP_NAME, A.GENDER, A.AGE, A.DEPT_ID, B.DEPT_ID, B.DEPT_NAME, B.USE_YN
FROM EMP_MASTER A LEFT OUTER JOIN DEPT_MASTER B ON A.DEPT_ID = B.DEPT_ID
ORDER BY A.EMP_ID;

SELECT *
FROM EMP_MASTER A, DEPT_MASTER B, ADDRESS_MASTER C
WHERE A.DEPT_ID = B.DEPT_ID AND A.ADDRESS_ID = C.ADDRESS_ID
ORDER BY A.EMP_ID;

--ANSI QUERY를 사용한 INNER JOIN 2번
SELECT *
FROM EMP_MASTER A INNER JOIN DEPT_MASTER B ON A.DEPT_ID = B.DEPT_ID INNER JOIN ADDRESS_MASTER C ON A.ADDRESS_ID = C.ADDRESS_ID
ORDER BY A.EMP_ID;

SELECT *
FROM EMP_MASTER A, DEPT_MASTER B
WHERE A.DEPT_ID = B.DEPT_ID(+)
ORDER BY A.EMP_ID;


--실습예제1
SELECT 
    B.DEPTNO,
    B.DNAME,
    A.EMPNO,
    A.ENAME,
    A.SAL
FROM EMP A INNER JOIN DEPT B ON A.DEPTNO = B.DEPTNO AND A.SAL>2000;


--실습예제2
SELECT
    B.DEPTNO,
    B.DNAME,
    A.EMPNO,
    A.ENAME,
    A.JOB,
    A.SAL
FROM EMP A RIGHT OUTER JOIN DEPT B ON A.DEPTNO = B.DEPTNO
ORDER BY B.DEPTNO,A.ENAME;


---실습예제3
SELECT
    B.DEPTNO,
    B.DNAME,
    A1.EMPNO,
    A1.ENAME,
    A1.MGR,
    A1.SAL,
    A1.DEPTNO,
    C.LOSAL,
    C.HISAL,
    C.GRADE,
    A2.EMPNO AS MGR_EMPNO,
    A2.ENAME AS MGR_ENAME
FROM EMP A1 LEFT OUTER JOIN EMP A2 ON A1.MGR=A2.EMPNO 
RIGHT OUTER JOIN SALGRADE C ON A1.SAL BETWEEN C.LOSAL AND C.HISAL 
RIGHT OUTER JOIN DEPT B ON A1.DEPTNO = B.DEPTNO
ORDER BY B.DEPTNO, A1.EMPNO;


select 

    